### ISSUE TITLE
NPM v7 support?

### ISSUE THREAD

**Issue by leepowelldev** [Ginxo/lock-treatment-tool#8]
NPM v7 now includes an additional field in the package-lock.json file of 'packages' - it seems this also contains resolved fields that need to be treated in order for a successful change of registry to work.

Happy to work on a PR if you'd be keen to support?

**Comment by Ginxo** [comment]
@leepowelldev thanks for creating this issue. We will need this change for our Red Hat community projects so it would be very nice thing to have. This should be a very simple change and I'm obviously glad to support you in your PR adventure.

**I would:**
Add this line after https://github.com/Ginxo/lock-treatment-tool/blob/0f70e13adbe00c4dc5af193302ae1a392c54911b/lib/treat-locks/npm.lock.js#L62
`treatFields(json.packages, npmOptions);`

I would replace `treatFields` method from https://github.com/Ginxo/lock-treatment-tool/blob/master/lib/treat-locks/npm.lock.js#L25 by

```
function treatFields(dependencies, npmOptions = new NpmOptions()) {
  if (npmOptions.replacePackageLockRegistry === true) {
    if (npmOptions.registry === undefined) {
      throw Error('replacePackageLockRegistry flag defined but registry');
    }
  }
  Object.keys(dependencies).forEach((prop) => {
    const dependency = dependencies[prop];
    if(typeof dependency === 'object') {
      if (npmOptions.replacePackageLockRegistry === true
        && npmOptions.registry !== undefined
        && dependency.resolved !== undefined) {
        dependency.resolved = commonLock.replaceHost(dependency.resolved, npmOptions.registry);
      } else {
        delete dependency.resolved;
      }
      if (npmOptions.skipIntegrity !== true) {
        delete dependency.integrity;
      }
      if (dependency.dependencies) {
        treatFields(dependency.dependencies, npmOptions);
      }
    }
  });
}
```
 (just `if(typeof dependency === 'object') {` added to https://github.com/Ginxo/lock-treatment-tool/blob/0f70e13adbe00c4dc5af193302ae1a392c54911b/lib/treat-locks/npm.lock.js#L33)

**In order to test it**

1. duplicate https://github.com/Ginxo/lock-treatment-tool/blob/master/__test__/treat-locks/npm.lock.test.js as npmv7.lock.test.js
2. create a new assertion statement for every test method from the new npmv7.lock.test.js file like `expect(checkDependencies(json.packages, undefined)).toBe(true);` (obviously modify `npmOptions` from every test method)
3. create a new `npmv7` folder https://github.com/Ginxo/lock-treatment-tool/tree/master/__test__/resources and paste there a v7 lock file
4. New test file will take resources from `./__test__/resources/npmv7`
5. Run `npm test`

**Final steps**

1. Add a new entry on https://github.com/Ginxo/lock-treatment-tool/blob/master/CHANGES.md
2. Increase version to `0.4.2` (since everything should work in the same way for the projects pointing to `^0.4.1`)

> Disclaimer: I'm writing down everything directly on github comment, I wouldn't discard typos here.

**Comment by leepowelldev** [comment]
https://github.com/Ginxo/lock-treatment-tool/pull/9
